<Project Sdk="NeoRuneExtended.Sdk/0.4.2">
  <PropertyGroup>
    <Version>1.0.2</Version>
    <NeoRuneModTitle>Stats Overlay</NeoRuneModTitle>
    <NeoRuneModDescription>See your Emeralds, Echo Shards, Enchantment Points, Soul Storms, and more all configurable in settings!</NeoRuneModDescription>
  </PropertyGroup>
</Project>
