<Project Sdk="NeoRuneExtended.Sdk/0.4.2">
  <PropertyGroup>
    <Version>1.0.3</Version>
    <NeoRuneModTitle>Better Gear</NeoRuneModTitle>
    <NeoRuneModDescription>Hide your armor and weapons, or wear any armor or weapon you've found (salvaged ones too) as a look over what you have on (only you see it).</NeoRuneModDescription>
  </PropertyGroup>
</Project>
